version: "3.0"

services:
  frontend:
    image: guiupssitech/youpssitech
    container_name: youpssitech-frontend
    expose:
      - 80
    environment:
      VIRTUAL_HOST: youpssitech.fr, www.youpssitech.fr
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: youpssitech.fr, www.youpssitech.fr
      LETSENCRYPT_EMAIL: guillaume.roussin44@gmail.com

  backend:
    image: augustodelg/pocketbase
    container_name: youpssitech-pocketbase
    volumes:
      - data:/pb_data:rw
    expose:
      - 8090
    environment:
      VIRTUAL_HOST: api.youpssitech.fr
      VIRTUAL_PORT: 8090
      LETSENCRYPT_HOST: api.youpssitech.fr
      LETSENCRYPT_EMAIL: guillaume.roussin44@gmail.com

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  data:
